CREATE TABLE patients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  date_of_birth DATE NOT NULL,
  state_case_number VARCHAR(50) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pharmacies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ncpdp_id VARCHAR(20) NOT NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  address VARCHAR(200),
  city VARCHAR(100),
  state VARCHAR(2) NOT NULL DEFAULT 'CO',
  zip VARCHAR(10)
);

CREATE TABLE unemployment_verifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES patients(id),
  cdle_claim_number VARCHAR(50) NOT NULL,
  status VARCHAR(20) NOT NULL,
  source VARCHAR(50) NOT NULL,
  raw_response VARCHAR(2000),
  verified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE prescriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES patients(id),
  pharmacy_id BIGINT NOT NULL REFERENCES pharmacies(id),
  drug_name VARCHAR(200) NOT NULL,
  ndc_code VARCHAR(20) NOT NULL,
  quantity INT NOT NULL,
  days_supply INT NOT NULL,
  prescriber_npi VARCHAR(20) NOT NULL,
  status VARCHAR(20) NOT NULL,
  retail_price_cents BIGINT NOT NULL,
  dispensed_at TIMESTAMP
);

CREATE TABLE reimbursement_claims (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prescription_id BIGINT NOT NULL REFERENCES prescriptions(id),
  verification_id BIGINT NOT NULL REFERENCES unemployment_verifications(id),
  state_program VARCHAR(100) NOT NULL,
  claim_amount_cents BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL,
  external_reference VARCHAR(100),
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decided_at TIMESTAMP
);

CREATE TABLE insurance_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  description VARCHAR(500),
  eligibility_summary VARCHAR(500),
  official_url VARCHAR(300)
);

CREATE TABLE insurance_match_recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES patients(id),
  summary VARCHAR(4000) NOT NULL,
  source_urls VARCHAR(2000),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed reference data: known Colorado public programs relevant to unemployed residents.
-- Curated as a fallback / starting point; the AI agent supplements this with live Tavily search.
INSERT INTO insurance_programs (name, description, eligibility_summary, official_url) VALUES
('Health First Colorado (Medicaid)', 'Colorado''s Medicaid program -- free or low-cost health coverage.', 'Income-based; many unemployed adults qualify at $0-low premium.', 'https://www.healthfirstcolorado.com'),
('Connect for Health Colorado', 'State health insurance marketplace; special enrollment period after job loss.', 'Loss of employer coverage triggers a 60-day special enrollment window.', 'https://connectforhealthco.com'),
('Colorado Indigent Care Program (CICP)', 'Discounted care at participating providers for low-income, uninsured residents.', 'Income up to 250% FPL; must apply through a participating clinic or hospital.', 'https://cdphe.colorado.gov/cicp'),
('OmniSalud (Colorado Option Marketplace)', 'State marketplace coverage that includes residents regardless of immigration status.', 'Income-based; covers populations excluded from the federal marketplace.', 'https://connectforhealthco.com/omnisalud');
