-- Dispense no longer defaults to $0 -- patient is billed at retail price, and the bill is
-- only cleared once a pharmacy appeal against an approved insurance application is paid.
ALTER TABLE prescriptions ADD COLUMN bill_status VARCHAR(30) NOT NULL DEFAULT 'PATIENT_OWES';
ALTER TABLE prescriptions ALTER COLUMN bill_status DROP DEFAULT;

-- The AI's recommendation becomes an actual application with a consent-gated lifecycle:
-- DRAFTED -> SUBMITTED (patient consented) or DECLINED -> APPROVED or DENIED (state decision,
-- recorded manually since there is no live state API to poll).
ALTER TABLE insurance_match_recommendations RENAME TO insurance_applications;
ALTER TABLE insurance_applications RENAME COLUMN summary TO ai_summary;
ALTER TABLE insurance_applications ADD COLUMN program_name VARCHAR(150);
ALTER TABLE insurance_applications ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'DRAFTED';
ALTER TABLE insurance_applications ALTER COLUMN status DROP DEFAULT;
ALTER TABLE insurance_applications ADD COLUMN consented_at TIMESTAMP;
ALTER TABLE insurance_applications ADD COLUMN consent_text VARCHAR(1000);
ALTER TABLE insurance_applications ADD COLUMN submitted_at TIMESTAMP;
ALTER TABLE insurance_applications ADD COLUMN decided_at TIMESTAMP;

-- Reimbursement claims are replaced by pharmacy appeals: filed by the pharmacy against an
-- approved insurance application (not a hardcoded state program), referencing the original
-- bill. No production data exists yet, so this is a clean drop and recreate rather than an
-- in-place column migration.
DROP TABLE reimbursement_claims;

CREATE TABLE pharmacy_appeals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prescription_id BIGINT NOT NULL REFERENCES prescriptions(id),
  insurance_application_id BIGINT NOT NULL REFERENCES insurance_applications(id),
  amount_cents BIGINT NOT NULL,
  status VARCHAR(20) NOT NULL,
  external_reference VARCHAR(100),
  submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  decided_at TIMESTAMP
);
