-- Copay assistance pairing: same consent-gated AI workflow as insurance_applications
-- (DRAFTED -> SUBMITTED/DECLINED -> APPROVED/DENIED), but for a different, adjacent
-- population -- commercially insured patients with a high copay, matched against
-- manufacturer and foundation copay assistance instead of state public programs.
CREATE TABLE copay_assistance_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150) NOT NULL UNIQUE,
  program_type VARCHAR(20) NOT NULL,
  description VARCHAR(500),
  eligibility_summary VARCHAR(500),
  official_url VARCHAR(300),
  -- Manufacturer copay cards are barred for Medicare/Medicaid patients under the federal
  -- anti-kickback statute (Section 1128B(b), Social Security Act); foundation/nonprofit
  -- assistance is not. Enforced in CopayAssistanceService, not just prompted to the AI.
  federal_program_safe BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE copay_assistance_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id BIGINT NOT NULL REFERENCES patients(id),
  program_name VARCHAR(150),
  ai_summary VARCHAR(4000) NOT NULL,
  source_urls VARCHAR(2000),
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFTED',
  consented_at TIMESTAMP,
  consent_text VARCHAR(1000),
  submitted_at TIMESTAMP,
  decided_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Seed reference data: well-known national copay assistance programs. Curated as a fallback /
-- starting point; the AI agent supplements this with live Tavily search, same pattern as
-- insurance_programs.
INSERT INTO copay_assistance_programs (name, program_type, description, eligibility_summary, official_url, federal_program_safe) VALUES
('PAN Foundation', 'FOUNDATION', 'Nonprofit copay assistance grants for underinsured patients across many diagnoses.', 'Income-based; open to commercially insured, Medicare, and Medicaid patients.', 'https://www.panfoundation.org', TRUE),
('HealthWell Foundation', 'FOUNDATION', 'Nonprofit copay, premium, and travel assistance for underinsured patients.', 'Income-based; open to commercially insured, Medicare, and Medicaid patients.', 'https://www.healthwellfoundation.org', TRUE),
('Patient Advocate Foundation Co-Pay Relief', 'FOUNDATION', 'Direct copay assistance for patients with specific diagnoses, including chronic and life-threatening conditions.', 'Income-based; open to commercially insured, Medicare, and Medicaid patients.', 'https://www.copays.org', TRUE),
('NeedyMeds Drug Discount Card', 'FOUNDATION', 'Free discount card usable at most pharmacies to lower cash price on many medications.', 'No income or insurance-status restriction; not usable in combination with insurance billing.', 'https://www.needymeds.org', TRUE),
('Manufacturer Copay Card', 'MANUFACTURER', 'Drug-specific card from the medication''s manufacturer that reduces or eliminates copay for that drug.', 'Commercially insured only. Federal law bars use by Medicare/Medicaid patients (anti-kickback statute).', 'https://www.needymeds.org/copay-cards', FALSE);
